sudo: false
language: php
php:
  - 5.4

before_install:
  - cd wp-content/plugins/yo-test/

install:
  - composer self-update;
  - composer install;

cache:
  directories:
  - wp-content/plugins/yo-test/vendor

script:
  - composer ci
